<a href="https://colab.research.google.com/github/gurtodi/GB_Python-lib-Numpy-Matplotlib-Scikit-learn/blob/main/Lesson_1_hw.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.Вычисления с помощью Numpy

## Задание 1.1

Импортируйте библиотеку Numpy и дайте ей псевдоним np.

In [ ]:
import numpy as np

Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. 
> Будем считать, что каждый столбец - это признак, а строка - наблюдение.

In [ ]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]], dtype=int)
print(a)
print(a[0][0])
type(a[0][0])

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]
1


numpy.int64

Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [ ]:
mean_a = (a.mean(axis=0))
mean_a

array([2. , 8.4])

## Задание 1.2
Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.





In [ ]:
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

## Задание 1.3
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp.

In [ ]:
a_centered_sp = np.dot(a_centered[:,0], a_centered[:,1])
print(a_centered_sp)
#0.394

8.0


Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [ ]:
print(a_centered_sp / (a.shape[0]-1))
#print(a_centered_sp / (len(a)-1))

2.0


## Задание 1.4**
Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.

[Выборочная ковариация и выборочная дисперсия](https://studopedia.ru/9_153900_viborochnaya-kovariatsiya-i-viborochnaya-dispersiya.html)

В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция [np.cov](https://numpy.org/doc/stable/reference/generated/numpy.cov.html) должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [ ]:
a_cov = np.cov(a.T)
a_cov

array([[1. , 2. ],
       [2. , 4.3]])

# 2. Работа с данными в Pandas

## Задание 2.1
Импортируйте библиотеку Pandas и дайте ей псевдоним pd.

In [ ]:
import pandas as pd

Создайте [датафрейм](https://pandas.pydata.org/docs/reference/frame.html) authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].

In [ ]:
authors = pd.DataFrame({
    'author_id': [1, 2, 3],
    'author_name': ['Тургенев', 'Чехов', 'Островский']
})
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:  
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].

In [ ]:
books = pd.DataFrame({
    'author_id': [1, 1, 1, 2, 2, 3, 3],
    'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    'price': [450, 300, 350, 500, 450, 370, 290]
})
books

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

## Задание 2.2
Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.


In [ ]:
authors_price = pd.merge(authors, books, on='author_id', how='inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

## Задание 2.3
Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.


In [ ]:
top5 = authors_price.nlargest(5, 'price', keep='first')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

## Задание 2.4
Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.


In [122]:
authors_stat = authors_price.groupby('author_name').agg({'price': ['min', 'max', 'mean']}).rename(columns={'min':'min_price', 'max':'max_price', 'mean':'mean_price'}).reset_index()
authors_stat

author_name     price                      
              min_price max_price  mean_price
0  Островский       290       370  330.000000
1    Тургенев       300       450  366.666667
2       Чехов       450       500  475.000000

In [134]:
#попытка через сводную таблицу
authors_price.pivot_table('price', index = 'author_name', aggfunc={'price': ['min', 'max', 'mean']}).rename(columns={'min':'min_price', 'max':'max_price', 'mean':'mean_price'})

max_price  mean_price  min_price
author_name                                  
Островский       370.0  330.000000      290.0
Тургенев         450.0  366.666667      300.0
Чехов            500.0  475.000000      450.0

## Задание 2.5**
Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].

In [141]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

Просмотрите документацию по функции [pd.pivot_table](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.pivot_table.html) с помощью вопросительного знака.

In [132]:
pd.pivot_table?

Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy.
Назовите полученный датасет book_info.

In [142]:
book_info = pd.pivot_table(authors_price, index='author_name', columns='cover', values='price', aggfunc='sum', fill_value='0')
book_info

cover       мягкая твердая
author_name               
Островский     660       0
Тургенев       650     450
Чехов            0     950

Сохраните book_info [в формат pickle](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_pickle.html) под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2.

In [158]:
book_info.to_pickle('./book_info.pkl')

book_info2 = pd.read_pickle('./book_info.pkl')
book_info2



cover       мягкая твердая
author_name               
Островский     660       0
Тургенев       650     450
Чехов            0     950

 Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.

In [162]:
book_info.where(book_info.values == book_info2.values).notna()

cover        мягкая  твердая
author_name                 
Островский     True     True
Тургенев       True     True
Чехов          True     True